apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: banking-app
type: Opaque
stringData:
  DB_HOST: "faustina-capstone-mysql-db.c4z8e8yaslgg.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "bankingapp"
  DB_USER: "admin"
  DB_PASSWORD: "Faustina2024!"